Salvation/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.authtoken import views

urlpatterns = [
    path('admin/', admin.site.urls, ),
    path('api-token-auth/', views.obtain_auth_token, name='auth-token'),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('oauth.urls')),
    path('testcases/', include('testcases.urls'),name = 'testcases'),
]

handler400 = 'oauth.views.error_views.bad_request'
handler403 = 'oauth.views.error_views.permission_denied'
handler404 = 'oauth.views.error_views.page_not_found'
handler500 = 'oauth.views.error_views.server_error'
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/testcases/urls.py
from django.urls import path

from testcases.views import config_views,operation_views,script_views

app_name = 'testcases'
urlpatterns=[
    path('testcase_config/',config_views.config_list_view,name='testcase_config'),
    path('config_data/',config_views.get_all_config_file,name='config_data'),
    path('config_upload/',config_views.config_upload,name='config_upload'),
    path('config_delete_file/',config_views.config_delete_file,name='config_delete_file'),
    path('download_config_template_file/',config_views.download_config_template_file,name='download_config_template_file'),
    path('testcase_template/',config_views.template,name='testcase_template'),
    path('template_delete_file/',config_views.template_delete_file,name='template_delete_file'),
    path('related/',config_views.related,name='related'),
    #操作
    path('reuseCommonTestCases/',operation_views.reuseCommonTestCases,name='reuseCommonTestCases'),
    path('generateScript/',operation_views.generateScript,name='generateScript'),

    #脚本测试套件
    path('script_config/',script_views.script_config,name='script_config'),
    path('get_script_list/',script_views.get_script_list,name='get_script_list'),
    path('get_script_file_content/',script_views.get_script_file_content,name='get_script_file_content'),
    path('update_script_file_content/',script_views.update_script_file_content,name='update_script_file_content'),
    path('upload_script_component/',script_views.upload_script_component,name='upload_script_component'),
    path('upload_script_file_component/',script_views.upload_script_file_component,name='upload_script_file_component'),
    path('download_script_folder/',script_views.download_script_folder,name='download_script_folder'),
    path('delete_script_folder/',script_views.delete_script_folder,name='delete_script_folder'),
    #脚本基线包
    path('script_baseline/',script_views.script_baseline,name='script_baseline'),
    path('upload_script_baseline_component/',script_views.upload_script_baseline_component,name='upload_script_baseline_component'),
    path('get_script_baseline_name/', script_views.get_script_baseline_name, name='get_script_baseline_name'),
]

apps/testcases/views/script_views.py
# -*- coding: utf-8 -*-            
# @Author : libeijie
# @Time : 2023/9/19 15:29

import os
import json
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render
from django.http import JsonResponse,HttpResponse,FileResponse
from django.utils.encoding import escape_uri_path

from testcases.service.script.script_service import *


def script_config(request):
    '''
    脚本测试套件列表页
    :param request:
    :return:
    '''
    response =render(request, template_name='testcases/script_config.html', context={})
    return response

def get_script_list(request):
    '''
    获取db配置文件数据并跳转至配置文件列表页
    :param request:
    :return:
    '''
    #获取数据
    tags = request.GET.get('tags','0') #0-脚本套件；1-基线包
    scrser = ScriptService()
    if tags == '0':
        scirpt_component_list = scrser.get_all_script_component_path_data()
    else:
        scirpt_component_list = scrser.get_all_script_baseline_path_data()
    folders = scrser.build_folder_structure(scirpt_component_list)
    #转json
    folder_structure_dict = [scrser.folder_to_dict(folder) for folder in folders]
    result = {'code':200,'data':folder_structure_dict}
    return JsonResponse(result)

def get_script_file_content(request):
    '''
    获取脚本文件内容
    :param request:
    :return:
    '''
    #获取id
    script_path = request.GET.get('path',None)
    script_tags = request.GET.get('tags',0)
    scrser = ScriptService()
    data = scrser.get_script_content_by_path(script_path,int(script_tags))
    result = {'code': 200, 'data': data}
    return JsonResponse(result)

@csrf_exempt
def update_script_file_content(request):
    '''
    根据path更新文件内容，不涉及数据库
    :param request:
    :return:
    '''
    parameters = json.loads(request.body.decode('utf8'))
    file_path = parameters.get('path')
    file_content = parameters.get('content')
    scrser = ScriptService()
    result_msg = scrser.update_script_file_content_physically(file_path,file_content)
    result = {'code': 200, 'data': result_msg}
    return JsonResponse(result)

@csrf_exempt
def upload_script_component(request):
    '''
    上传脚本套件
    :param request:
    :return:
    '''
    upload_script_component_files = request.FILES.getlist('files[]', None)
    upload_script_component_file_paths = request.POST.getlist('file_paths[]', None)
    update_item_id = request.POST.get('update_item_id', '0') #如果是上传，则为0，如果是更新则为更新的数据id
    scrser = ScriptService()
    if update_item_id == '0': #上传
        result_msg = scrser.insert_script_component_folder(upload_script_component_files,upload_script_component_file_paths)
    else: #更新
        result_msg = scrser.update_script_component_folder(update_item_id,upload_script_component_files,upload_script_component_file_paths)
    result = {'code': 200, 'data': result_msg}
    return JsonResponse(result)

@csrf_exempt
def upload_script_file_component(request):
    '''
    上传脚本套件
    :param request:
    :return:
    '''
    upload_script_component_files = request.FILES.get('file', None)
    update_item_id = request.POST.get('update_item_id', '0') #如果是上传，则为0，如果是更新则为更新的数据id
    scrser = ScriptService()
    result_msg = scrser.update_script_component_file(update_item_id,upload_script_component_files)
    result = {'code': 200, 'data': result_msg}
    return JsonResponse(result)

def download_script_folder(request):
    '''
    下载文件（夹）
    :param request:
    :return:
    '''
    folder_id = request.GET.get('folder_id',None) #下载的文件（夹）id
    folder_tags = request.GET.get('tags',0) #下载的文件（夹）id
    folder,folder_name,flag = ScriptService().download_script_folder(folder_id,int(folder_tags))
    if flag: #文件
        if os.path.exists(folder):
            response = FileResponse(open(folder, 'rb'))
            response['Content-Type'] = 'application/octet-stream'  # 二进制文件
            response['Content-Disposition'] = 'attachment; filename={}'.format(escape_uri_path(folder_name))
    else: #文件夹打包成的zip
        # 构建HTTP响应，提供ZIP文件下载
        response = HttpResponse(folder.getvalue(), content_type="application/zip")
        response['Content-Disposition'] = 'attachment; filename={}.zip'.format(escape_uri_path(folder_name))
    return response

@csrf_exempt
def delete_script_folder(request):
    '''
    删除文件（夹）
    :param request:
    :return:
    '''
    parameters = json.loads(request.body.decode('utf8'))
    folder_id = parameters.get('folder_id') # 删除的文件（夹）id
    folder_tags = parameters.get('tags',0) # 删除的文件（夹）id
    result_msg = ScriptService().delete_script_folder(folder_id,int(folder_tags))
    result = {'code': 200, 'data': result_msg}
    return JsonResponse(result)


def script_baseline(request):
    '''
    脚本基线包列表页
    :param request:
    :return:
    '''
    response =render(request, template_name='testcases/script_baseline.html', context={})
    return response

@csrf_exempt
def upload_script_baseline_component(request):
    '''
    上传脚本基线包
    :param request:
    :return:
    '''
    upload_script_baseline_component_files = request.FILES.get('zipFile', None)
    scrser = ScriptService()
    result_msg = scrser.upload_script_baseline_folder(upload_script_baseline_component_files)
    result = {'code': 200, 'data': result_msg}
    return JsonResponse(result)


def get_script_baseline_name(request):
    '''
    获取基线包名称
    :param request:
    :return:
    '''
    level = request.GET.get('level', None)
    tags = request.GET.get('tags', None)
    script_baseline_names_ids = get_script_baselines_service(level,tags)
    result = {'code': 200, 'data': script_baseline_names_ids}
    return JsonResponse(result)

templates/includes/_pagination.html
<ul class="pagination m-auto">

    {% if page_objects.has_previous %}
        <li class="page-item "><a href="?page=1&orderby={{ orderby }}&search={{ search }}">
            <span class="page-link">&nbsp;首页</span></a></li>

        <li class="page-item "><a
                href="?page={{ page_objects.previous_page_number }}&orderby={{ orderby }}&search={{ search }}"><span
                class="page-link"><i
                class="fa fa-chevron-left" aria-hidden="true"></i>&nbsp;上一页</span></a></li>
    {% else %}

        <li class="page-item disabled"><a><span class="page-link">首页</span></a></li>
        <li class="page-item disabled"><a><span class="page-link">上一页&nbsp;<i
                class="fa fa-chevron-left" aria-hidden="true"></i></span></a></li>
    {% endif %}

    {% if page_objects.number|add:'-4' > 1 %}
        <li class="page-item"><a class="page-link"
                                 href="?page={{ page_objects.number|add:'-5' }}&orderby={{ orderby }}&search={{ search }}">&hellip;</a>
        </li>
    {% endif %}

    {% for i in page_objects.paginator.page_range %}
        {% if page_objects.number == i %}
            <li class="page-item active"><a class="page-link" href=""> {{ i }}</a></li>
        {% elif i > page_objects.number|add:'-5' and i < page_objects.number|add:'5' %}
            <li class="page-item"><a class="page-link"
                                     href="?page={{ i }}&orderby={{ orderby }}&search={{ search }}">{{ i }}</a></li>
        {% endif %}
    {% endfor %}


    {% if page_objects.paginator.num_pages > page_objects.number|add:'4' %}
        <li class="page-item"><a class="page-link"
                                 href="?page={{ page_objects.number|add:'5' }}&orderby={{ orderby }}&search={{ search }}">&hellip;</a>
        </li>
    {% endif %}

    {% if page_objects.has_next %}

        <li class="page-item"><a class="page-link"
                                 href="?page={{ page_objects.next_page_number }}&orderby={{ order }}&search={{ search }}">下一页&nbsp;<i
                class="fa fa-chevron-right" aria-hidden="true"></i></a></li>

        <li class="page-item"><a class="page-link"
                                 href="?page={{ page_objects.paginator.num_pages }}&orderby={{ order }}&search={{ search }}">尾页&nbsp;</a>
        </li>

    {% else %}
        <li class="page-item disabled"><a><span class="page-link">下一页&nbsp;<i
                class="fa fa-chevron-right" aria-hidden="true"></i></span></a></li>
        <li class="page-item disabled"><a><span class="page-link">尾页</span></a></li>
    {% endif %}

</ul>

templates/includes/navigation.html
<!-- NOT IMPLEMENTED -->
<!-- {% load static %} -->


<nav class="navbar navbar-light  justify-content-between">
    <div class="col-6">
    </div>

    <div class="col-2 ">
        <div class="nav-item dropdown float-right">

            <h8
                    class="nav-link dropdown-toggle"
                    href="#"
                    id="navbarDropdown"
                    data-toggle="dropdown"
                    aria-haspopup="true"
                    aria-expanded="false">
                {% if user.gender == 'female' %}
                    <img src="{% static '/assets/images/user/avatar-1.jpg' %}"
                         style="width:30px;height:30px;border-radius:50%;"
                         alt="">
                {% else %}
                    <img src="{% static '/assets/images/user/avatar-2.jpg' %}"
                         style="width:30px;height:30px;border-radius:50%;"
                         alt="">

                {% endif %}

                {{ user.username}}

            </h8>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'logout' %}">登出</a>
            </div>
        </div>
    </div>
</nav>

templates/includes/scripts.html
{% load static %}
    <!-- Required Js -->

    <script src="{% static 'assets/js/vendor-all.min.js' %}"></script>
    <script src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/pcoded.min.js' %}"></script>
    <script src="{% static 'assets/plugins/fileinput.js' %}"></script>
    <script src="{% static 'assets/plugins/locales/zh.js' %}"></script>
    <script src="{% static 'assets/plugins/locales/ar.js' %}"></script>
    <script src="{% static '/themes/explorer/theme.js' %}"></script>
    <script src="{% static 'assets/plugins/bootbox.js' %}"></script>
    <script src="{% static 'assets/plugins/bootbox_zh_CN.js' %}"></script>

templates/includes/sidebar.html
<nav class="pcoded-navbar">
    <div class="navbar-wrapper">
        <div class="navbar-brand header-logo">
            <a target="_blank"
               href="" class="b-brand">
                <div class="b-bg">
                    <i class="feather icon-trending-up"></i>
                </div>
                <span class="b-title">自动化平台</span>
            </a>
            <a class="mobile-menu" id="mobile-collapse" href="javascript:"><span></span></a>
        </div>
        <div class="navbar-content scroll-div">
            <ul class="nav pcoded-inner-navbar">

                <li data-username="dashboard Default Ecommerce CRM Analytics Crypto Project"
                    class="nav-item ">
                    <a href="{% url 'index' %}" class="nav-link "><span class="pcoded-micon"><i
                            class="feather icon-home"></i></span><span class="pcoded-mtext">首页</span></a>
                </li>


                <li class="nav-item ">
                    <a href="{% url 'userlist' %}" class="nav-link ">
                            <span class="pcoded-micon"><i
                                    class="fa fa-users"></i>
                        </span>
                        <span class="pcoded-mtext">用户管理</span></a>
                </li>


                <!-- 项目管理 -->

{#                <li class="nav-item pcoded-hasmenu ">#}
{#                    <a href="javascript:" class="nav-link "><span class="pcoded-micon"><i class="feather icon-box"></i></span><span#}
{#                            class="pcoded-mtext">项目管理</span></a>#}
{#                    <ul class="pcoded-submenu">#}
{#                            <li>#}
{#                                <a><span class="pcoded-mtext">变量管理#}
{#                                    <ul class="pcoded-submenu">#}
{#                                        <li class=""><a class=""  href="{% url 'devlist' %}" >公共变量</a></li>#}
{#                                        <li class=""><a class="" href="{% url 'enviroment_bianliang' %}">环境变量</a></li>#}
{#                                        <li class=""><a class="" href="{% url 'zidingyi_bianliang' %}">自定义变量</a></li>#}
{#                                    </ul>#}
{#                                </span></a>#}
{#                            </li>#}
{#                        <li class=""><a href="{% url 'modulelist' %}" class="">模块信息</a></li>#}
{#                        <li class=""><a href="{% url 'prlist' %}" class="">项目信息</a></li>#}
{##}
{#                    </ul>#}
{#                </li>#}

                <!-- Management Category -->

                <li class="nav-item pcoded-hasmenu ">
                    <a href="javascript:" class="nav-link "><span class="pcoded-micon"><i class="fa fa-bars"></i></span><span
                            class="pcoded-mtext">用例管理</span></a>

                    <ul class="pcoded-submenu">

{#                        <li class="nav-item pcoded-hasmenu ">#}
{#                            <a href="javascript:" class="nav-link "><span class="pcoded-mtext">用例文件</span></a>#}
{#                            <ul class="pcoded-submenu">#}
{#                                <li class=""><a href="{% url 'testcases:case' %}" class="">配置文件</a></li>#}
{#                                <li class=""><a href="{% url 'testcases:template' %}" class="">模板文件</a></li>#}
{#                            </ul>#}
{#                        </li>#}
{##}
{#                        <li class="nav-item pcoded-hasmenu ">#}
{#                            <a href="javascript:" class="nav-link "><span class="pcoded-mtext">脚本文件</span></a>#}
{#                            <ul class="pcoded-submenu">#}
{#                                <li class=""><a href="{% url 'testcases:case' %}" class="">基线包</a></li>#}
{#                                <li class=""><a href="{% url 'testcases:template' %}" class="">测试套件</a></li>#}
{#                            </ul>#}
{#                        </li>#}

                        <li class=""><a href="{% url 'testcases:testcase_config' %}" class="">用例配置文件</a></li>
                        <li class=""><a href="{% url 'testcases:testcase_template' %}" class="">用例模板文件</a></li>
                        <li class=""><a href="{% url 'testcases:script_config' %}" class="">脚本测试套件</a></li>
                        <li class=""><a href="{% url 'testcases:script_baseline' %}" class="">脚本基线包</a></li>

                        <li class=""><a href="{% url 'testcases:related' %}" class="">相关操作</a></li>
                    </ul>

                </li>

{#                <li class="nav-item pcoded-hasmenu ">#}
{#                    <a href="javascript:" class="nav-link "><span class="pcoded-micon"><i#}
{#                            class="fa fa-tasks"></i></span><span#}
{#                            class="pcoded-mtext">任务管理</span></a>#}
{#                    <ul class="pcoded-submenu">#}
{#                        <li class=""><a href="{% url 'checklist' %}" class="">任务详情</a></li>#}
{#                    </ul>#}
{#                </li>#}

{#                <li class="nav-item pcoded-hasmenu ">#}
{#                    <a href="javascript:" class="nav-link "><span class="pcoded-micon"><i#}
{#                            class="fa fa-tasks"></i></span><span#}
{#                            class="pcoded-mtext">工具合集</span></a>#}
{#                    <ul class="pcoded-submenu">#}
{#                        <li class=""><a href="{% url 'checklist' %}" class="">dependency-(安全扫描)</a></li>#}
{#                        <li class=""><a href="{% url 'xraylist' %}" class="">Xray-(sql注入扫描)</a></li>#}
{#                        <li class=""><a href="{% url 'aes' %}" class="">加解密</a></li>#}
{#                        <li class=""><a href="{% url 'ftp' %}" class="">FTP文件下载</a></li>#}
{#                    </ul>#}
{##}
{#                </li>#}

                <li class="nav-item ">
                    <a href="" class="nav-link ">
                        <span class="pcoded-micon">
                            <i class="fa fa-bookmark"></i>
                        </span><span class="pcoded-mtext">记录操作 </span></a>
                </li>

                {% if user.is_superuser %}  <!-- 管理员权限 -->
                    <li class="nav-item ">
                        <a href="/admin/" class="nav-link ">
                        <span class="pcoded-micon"><i
                                class="fas fa-shield-alt"></i>
                    </span>
                            <span class="pcoded-mtext">后台管理</span></a>
                    </li>
                {% endif %}

                <li data-username="Disabled Menu" class="nav-item">
                    <a href="" class="nav-link">
                        <span class="pcoded-micon"><i class="feather icon-power"></i></span><span class="pcoded-mtext">Logout</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>